name: Master push CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  send-project:
    name: Sends project to server

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Archive project
        working-directory: .
        run: |
          zip -r app.zip . -x "*.git*" -x "*.idea*"
        shell: bash

      - name: echo
        working-directory: .
        run: |
          ls -la
        shell: bash

      - name: Copy project archive file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./app.zip"
          target: "/home/${{ secrets.SERVER_USER }}/app"

  deploy:
    name: Deploy project to server

    needs:
      - send-project

    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        id: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            unzip ~/app/app.zip -d ~/app \
            && bash ~/app/deploy.sh